### ISSUE TITLE
Fills up disk after a long time of running

### ISSUE THREAD

**Issue by oxagast** [oxagast/oxadio#2]
After fixing the no volume control bug, another issue has arose.  I solved it by creating a `.wav` file containing the stream in a temporary directory, but realized that without truncating the beginning of the `.wav` it would inevitably fill up the hard drive, or more probably, hit the limitation of the filesystem it's writing to's max file size.  Will have to consider how this should be fixed, either as a stream that never writes to the storage (ideal), or a buffer file that gets truncated on a timer.

**Comment by ghost** [comment]
It is not just your app, [it is WAV](https://forum.audacityteam.org/viewtopic.php?t=10777). I when program such things just tell the app to see the input as truncated. Because this is necessary for websites, this is very common for a web dev to do with logins because if you notice a single space at the end of a login does not work if the dev has not made a way for the program to see it as truncated. I would just use the same trick. Create a variable for the title and tell the program to remove spaces and whitespace, but do not change the filename. I normally do not address issues, and I thought maybe you already thought of this. Just a suggestion. I am going to try out your addon tonight on <strikethrough>LibreELEC</strikethrough>. Well, I will try it on OSMC anyway. You know I keep forgetting LibreELEC is read-only.

**Comment by oxagast** [comment]
Thank you for the suggestion, I'll try that. I haven't taken a look at this code in a while, but IIRC my problem was trying to figure out how to truncate the file "in reverse" if that makes sense without interfering with playback at truncate time. Let me know if this works at all on LibreELEC, I've only tested this on OSMC on a Rasperry Pi 3b+ (all I have access to, currently.)

**Comment by ghost** [comment]
You know I forgot LibreELEC is read-only. Doh! I will test it on several platforms. I mess with Kodi all the time. I have played with it so much I might fork it soon. But I plan on testing a list of addons on Manjaro ARM and real Debian on Raspberry Pi. I guess though I could try building and compiling LibreELEC with the addon. That may be a bit of a project, but I have done it before. I think they made it easier to build over the years.

**Comment by ghost** [comment]
I have a question. Have you tried compiling this addon from source? You know the way I have done it with addons like yours in the past is I drop the addon in just before I compile it with the rest of Kodi. Then what I do is make a zip file of the folder afterward, and give it an appropriate name. Such as if I compile it on Manjaro ARM, I add that to the file name.  Another thing is on Linux, I have to wonder as far as basic dependencies and package names. While package maintainers try to keep it together, you often need distro dependencies that may have slightly different package names. As I am sure you well know.

So, I was considering creating a few containers, and trying out some addons after compiling Kodi. That though means creating like a `.deb` package, etc. You can even create a distro package for your addon using package maintainer guidelines. And the reason I say all that is it is not working on Manjaro so far. I have more time to build and compile today than yesterday.

**Comment by oxagast** [comment]
I could crate a deb package but I'm trying to keep it so that it can be installed from within Kodi.  One mistake a made though was on my install of OSMC I already had rtl-sdr and sox installed before I wrote kadio, so the depenancies were unmet on most boxes people tried to install it on, and without taking a look at the code you wouldn't know you needed those two plus a few of their own depanancies respectively.  It should be fixed now so that on first run it tries to install those apps, but it as a kinda afterthought fix and the "problem" isn't well solved.  I'm still trying to decide what route I should take.

**Comment by ghost** [comment]
Why not use another format? Why use .wav? It is only a `.wav` issue from my reading on some of these similar issues was looking for a resolution elsewhere and ended up once again entertaining myself with Kodi. I also started scratching some possibilities that I am currently using to get it going on any platform. This my first real try at Python so it may not be as clean as it should be, but [here is what I put togethe](https://drive.google.com/file/d/1u_IwYw50AAsEEf0v5-J8i2lG4wuNs4vq/view?usp=sharing)r to try and install it to Manjaor, but I was also going to change the format from `.wav` to something else.  It is probably not final, but I am done for the day. I was reading about Python all day. I am interested in Python now.

**Comment by oxagast** [comment]
I couldn't figure out how to get it to support anything but .wav.  If you know of the command to make it go to .mp3 or something, let me know.

**Comment by oxagast** [comment]
One issue with your edits is that on OSMC sudo is allowed without a password (this is by design for simplicity)... but this is not the case on _most_ installations.  For security purposes its also difficult to push even a known password to sudo, even more so from inside Kodi (and probably insecure).

Maybe I should just put in the readme that if you're going to install on anything except OSMC or very similar clones of it, that you'll need to install rtl-sdr and sox as dependencies?

**Comment by ghost** [comment]
The only way to make it easy would seem to be creating a package for use with a package manager. I use `checkinstal`l for that. I have not yet built other packages. I wonder if the `fakeroot `command would work?

**Comment by ghost** [comment]
This might [offer some insight](https://wiki.python.org/moin/Audio). I would write a script to decide if it is on Windows or Linux and as you can see, or it seems to support formats for direclty accessing sound devices. That would be very interesting, if that is what that does.

**Comment by ghost** [comment]
Even could do something like this perhaps?

```
sudo apt-get install fakeroot  -y
wget http://github.com/oxagast/kadio/some-zip-file.zip
unzip some-zip-file-.zip -d /usr/share/kodi/addons
cd /usr/share/kodi/addons/some-zip-file
dpkg-buildpackage -rfakeroot
sudo dpkg -i kadio.deb
```
I will definitely look at it again tomorrow.

**Comment by oxagast** [comment]
Got an mp3 stream to work with mp3 lame.

**Comment by oxagast** [comment]
The relevant line in the fix is this:
`cmd = "sudo rtl_fm -f " + station + "." + decimal + "M -g 50 -M fm -s 200k -A std -l 0 -E deemp -r 75k | lame -r -s 75 -V 5 --lowpass 15 --resample 44.1 -m m -b 64 - " + audiof + " &"`

**Comment by ghost** [comment]
Thanks. I will test it later this afternoon most likely when I return to my Raspberry Pi.

**Comment by oxagast** [comment]
Closing this issue, thanks your your help w3tech.
